### ISSUE TITLE
lxd formula can't work with salt 2018.3.0

### ISSUE THREAD

**Issue by DeadlyMercury** [pcdummy/saltstack-lxd-formula#6]
https://github.com/saltstack/salt/issues/46903

```
[ERROR   ] Failed to import module lxd, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1459, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/modules/lxd.py", line 114, in <module>
    @salt.utils.decorators.which('lxd')
AttributeError: 'module' object has no attribute 'which'
```

> The lxd formula issue seems to be using a custom module that might need to be updated for some changes around utils that went into 2018.3.
